name: Run Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gotest:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.20.1'

    - name: Copy test config.yaml
      run: cp config.yaml.example config.yaml

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
